# https://github.com/mojombo/jekyll/wiki/Configuration

# Don't use custom plugins
safe: true

baseurl: /
url: http://marc.helbling.fr
name: marchelbling
description:  A blog you should read *later*

# Site source
source: .
# Where to put the compiled site
destination: ./_site

## Markdown engine
markdown: kramdown
kramdown:
    auto_ids: true
    auto_id_stripping: true
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        css_class: 'highlight'

highlighter: rouge

# Exclude these files from compilation
exclude: [Gemfile, Gemfile.lock, CNAME, README.md, vendor]

# Don't produce a 'related posts' index
lsi: false

# Permalink style
permalink: /:year/:month/:title
